"""empty message

Revision ID: 924af3902c8d
Revises: 
Create Date: 2018-03-03 01:04:50.659158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924af3902c8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    op.drop_table('user')
    # ### end Alembic commands ###
