"""empty message

Revision ID: 76baf4c27890
Revises: 0a0e3e339ec9
Create Date: 2018-02-14 02:52:59.391584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76baf4c27890'
down_revision = '0a0e3e339ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_created_at'), 'todo', ['created_at'], unique=False)
    op.create_index(op.f('ix_todo_finished_at'), 'todo', ['finished_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_finished_at'), table_name='todo')
    op.drop_index(op.f('ix_todo_created_at'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
